server:
  port: 8001
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/command-manage?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: root
    password: cxwCXW123

mybatis-plus:
  mapper-locations: "classpath*:com/chenx/**/mapper/sql/*.xml"

custom:
  swagger:
    enabled: true
    basePackages:
      - com.chenx.command
# 日志配置
logging:
  level:
    root: info
  config: classpath:config/log/logback.xml
